site_name: Sneaked In Academy Guides
site_description: Guides and resources for EVE Online players
site_author: Sneaked In
site_url: https://sneakedinacademy.github.io/

theme:
  name: material
  palette:
    scheme: slate
    primary: indigo
    accent: blue
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - content.code.copy

nav:
  - Home: index.md

  - Getting Started:
      - Overview: getting-started/index.md
      - Wichtige Skills erklärt: getting-started/basic-skills.md
      - D-Scan Nutzung: getting-started/d-scan-basics.md
      - Flottenbefehle: getting-started/fleet-commands.md
      - Flottenverhalten: getting-started/fleet-discipline.md
      - Skillplans Overview:
        - Mining Skillplan Light: getting-started/skill-plans-overview/mining-light.md
        - Interceptor Skillplan Light: getting-started/skill-plans-overview/interceptor-skillplan-light.md
        - Magic 14 Light: getting-started/skill-plans-overview/magic-14-light.md
        - Pioneer Minimal: getting-started/skill-plans-overview/minimal-pioneer.md
        - Barges Minimal: getting-started/skill-plans-overview/minimal-barges.md

  - Ships:
      - Overview: ships/index.md
      - Frigates & Destroyers:
          - Kikimora: ships/frigates-destroyers/kikimora.md
      - Beginner Cruisers:
          - Caracal: ships/beginner_cruisers/caracal.md
          - Rupture: ships/beginner_cruisers/rupture.md
      - Advanced:
          - Eagle: ships/advanced/eagle.md
      - Support:
          - T1 Logistics: ships/support/t1-logistics.md

  - Fitting:
      - Overview: fittings/index.md
      - Faction Warfare:
          - Overview: fittings/faction-warfare/index.md
          - Slasher FW: fittings/faction-warfare/slasher-fw.md
      - Abyss:
          - Overview: fittings/abyss/index.md
          - Single:
              - Overview: fittings/abyss/single/index.md
              - Gila T4: fittings/abyss/single/gila-t4.md
          - Duo:
              - Overview: fittings/abyss/duo/index.md
          - Trio:
              - Overview: fittings/abyss/trio/index.md
      - Missions:
          - Overview: fittings/missions/index.md
          - Security:
              - Overview: fittings/missions/security/index.md
              - Caracal L2: fittings/missions/security/caracal-l2.md
          - Distribution:
              - Overview: fittings/missions/distribution/index.md
          - Mining:
              - Overview: fittings/missions/mining/index.md
      - Mining:
          - Overview: fittings/mining/index.md
          - Frigates:
              - Overview: fittings/mining/frigates/index.md
              - Venture Highsec: fittings/mining/frigates/venture-highsec.md
          - Destroyers:
              - Overview: fittings/mining/destroyers/index.md
          - Barges:
              - Overview: fittings/mining/barges/index.md
          - Exhumers:
              - Overview: fittings/mining/exhumers/index.md
      - Logistics:
          - Overview: fittings/logistics/index.md
          - T1 Logi Basic: fittings/logistics/t1-logi-basic.md
      - Hauler:
          - Overview: fittings/hauler/index.md
          - Fast Align: fittings/hauler/fast-align.md

  - Missions:
      - Overview: missions/index.md
      - Security: missions/security.md
      - Mining: missions/mining.md
      - Distribution: missions/distribution.md
      - Epic Arcs:
          - Overview: missions/epic-arcs/index.md
          - The Blood-Stained Stars: missions/epic-arcs/the-blood-stained-stars.md
          - Empire Epic Arcs: missions/epic-arcs/empire-epic-arcs.md

  - Exploration:
      - Overview: exploration/index.md
      - Scanning: exploration/scanning.md
      - Hacking: exploration/hacking.md
      - Relic & Data Sites: exploration/sites.md

  - Wormholes:
      - Overview: wormholes/index.md
      - Basics: wormholes/basics.md
      - Safety: wormholes/safety.md

  - Abyss:
      - Overview: abyss/index.md
      - zero-to-omega:
            - Overview: abyss/zero-to-omega/index.md
            - Step 1: abyss/zero-to-omega/step1.md
            - Step 2: abyss/zero-to-omega/step2.md
            - Step 3: abyss/zero-to-omega/step3.md
            - Step 4: abyss/zero-to-omega/step4.md

  - Faction Warfare:
      - Overview: faction-warfare/index.md
      - Basics: faction-warfare/fw-basics.md
      - Site Types: faction-warfare/fw-sites.md

  - Industry:
      - Basics: industry/index.md
      - Mining:
          - Basics: industry/mining/mining-basics.md
          - Ores: industry/mining/ores.md
          - Moon Ores: industry/mining/moon-ores.md
          - Ice: industry/mining/ice.md
          - Gas: industry/mining/gas.md
          - Waste: industry/mining/mining-waste.md
          - Critical-Hits: industry/mining/mining-critical-hits.md
      - Production:
          - Basics: industry/production/index.md
      - Research:
          - Basics: industry/research/index.md
      - Planetary Interaction:
          - Basics: industry/planetary-interaction/index.md
      - Reactions: industry/reactions.md

  - Links:
      - Overview: links/index.md
      - Maps: links/maps.md
      - Market: links/market.md
      - Fitting Tools: links/fitting-tools.md
      - Killboards: links/killboards.md
      - Forums: links/forums.md
      - Discord: links/discord.md
      - Resources: links/resources.md
      - Calculators: links/calculators.md

plugins:
  - search

markdown_extensions:
  - admonition
  - attr_list
  - toc:
      permalink: true

extra_css:
  - stylesheets/extra.css
